Repository ethereum/trinity, pull requests merged in 2019-05, with the labels that each got.

#550 Rename and reorder `PendingAttestationRecord` fields
  eth2/beacon/epoch_processing_helpers.py
  eth2/beacon/state_machines/forks/serenity/operation_processing.py
  eth2/beacon/types/pending_attestation_records.py
  tests/eth2/beacon/conftest.py
  tests/eth2/beacon/state_machines/forks/test_serenity_epoch_processing.py
  tests/eth2/beacon/test_epoch_processing_helpers.py
  tests/eth2/beacon/types/test_pending_attestation_record.py
Labels: eth2.0

#549 Fix RANDAO message_hash
  eth2/beacon/state_machines/forks/serenity/block_validation.py
  eth2/beacon/tools/builder/proposer.py
Labels: eth2.0

#551 Fix `_compute_inactivity_leak_deltas`
  eth2/beacon/state_machines/forks/serenity/epoch_processing.py
Labels: eth2.0

#568 remove 99th percentile timeout
  trinity/protocol/common/managers.py
Labels: PR state: needs review

#542 remove legacy pypi markdown approach using pandoc
  setup.py
  tox.ini
Labels: PR state: needs review

#571 Move uptime tracking to base service class
  p2p/_utils.py
  p2p/peer.py
  p2p/peer_pool.py
  p2p/service.py
Labels: PR state: needs review

#558 Piper/blacklist peers who send malformed messages
  p2p/constants.py
  p2p/peer.py
Labels: PR state: needs review

#570 Remove the un-used humanize utils
  tests/core/_utils/test_humanize.py
  trinity/_utils/humanize.py
  trinity/sync/common/headers.py
  trinity/sync/full/chain.py
Labels: PR state: needs review

#565 Remove mutable data structures from p2p.protocol classes
  p2p/p2p_proto.py
  p2p/protocol.py
  p2p/tools/paragon/commands.py
  p2p/tools/paragon/proto.py
  trinity/protocol/bcc/commands.py
  trinity/protocol/bcc/proto.py
  trinity/protocol/eth/commands.py
  trinity/protocol/eth/proto.py
  trinity/protocol/les/commands.py
  trinity/protocol/les/proto.py
Labels: PR state: needs review

#579 Remove `Record` suffix
  eth2/beacon/committee_helpers.py
  eth2/beacon/deposit_helpers.py
  eth2/beacon/epoch_processing_helpers.py
  eth2/beacon/helpers.py
  eth2/beacon/on_genesis.py
  eth2/beacon/state_machines/forks/serenity/block_validation.py
  eth2/beacon/state_machines/forks/serenity/epoch_processing.py
  eth2/beacon/state_machines/forks/serenity/operation_processing.py
  eth2/beacon/types/attestation_data.py
  eth2/beacon/types/crosslinks.py
  eth2/beacon/types/pending_attestations.py
  eth2/beacon/types/states.py
  eth2/beacon/types/validators.py
  tests/core/p2p-proto/bcc/test_commands.py
  tests/eth2/beacon/conftest.py
  tests/eth2/beacon/helpers.py
  tests/eth2/beacon/state_machines/forks/test_serenity_block_attestation_validation.py
  tests/eth2/beacon/state_machines/forks/test_serenity_epoch_processing.py
  tests/eth2/beacon/test_deposit_helpers.py
  tests/eth2/beacon/test_epoch_processing_helpers.py
  tests/eth2/beacon/test_helpers.py
  tests/eth2/beacon/test_on_genesis.py
  tests/eth2/beacon/types/test_crosslink_record.py
  tests/eth2/beacon/types/test_pending_attestation_record.py
  tests/eth2/beacon/types/test_states.py
  tests/eth2/beacon/types/test_validator_record.py
  trinity/protocol/bcc/commands.py
  trinity/protocol/bcc/proto.py
Labels: eth2.0

#559 Blacklist peers who send invalid responses
  trinity/protocol/common/managers.py
Labels: PR state: needs review

#569 Piper/better messaging on header validation failure
  docs/conf.py
  tests/core/p2p-proto/test_headers_request_validator.py
  tests/core/test_humanize_integer_sequence.py
  trinity/_utils/humanize.py
  trinity/protocol/common/validators.py
Labels: PR state: needs review

#555 Extend blacklisting to peer behavior to peer request timeouts.
  p2p/constants.py
  p2p/peer.py
  trinity/protocol/common/constants.py
  trinity/protocol/common/managers.py
Labels: PR state: needs review

#564 Extract sub proto selection to utility
  p2p/exceptions.py
  p2p/peer.py
  p2p/protocol.py
  p2p/tools/paragon/helpers.py
  p2p/tools/paragon/peer.py
  tests/core/p2p-proto/test_peer.py
  tests/p2p/test_match_protocols_with_capabilities.py
  trinity/protocol/bcc/peer.py
  trinity/protocol/eth/peer.py
  trinity/protocol/les/peer.py
Labels: PR state: needs review

#547 Update finalization and justification in the DB
  eth2/beacon/chains/base.py
  eth2/beacon/db/chain.py
  eth2/beacon/db/exceptions.py
  eth2/beacon/db/schema.py
  eth2/beacon/types/blocks.py
  tests/eth2/beacon/chains/conftest.py
  tests/eth2/beacon/chains/test_beacon_chain.py
  tests/eth2/beacon/chains/test_chains.py
  tests/eth2/beacon/db/test_beacon_chaindb.py
  tests/eth2/beacon/state_machines/forks/test_serenity_operation_processing.py
  tests/eth2/beacon/state_machines/test_demo.py
  tests/eth2/beacon/state_machines/test_state_transition.py
  tests/eth2/beacon/types/test_block.py
  tests/plugins/eth2/beacon/test_validator.py
  trinity/config.py
  trinity/db/beacon/manager.py
  trinity/plugins/eth2/beacon/plugin.py
  trinity/sync/beacon/chain.py
Labels: eth2.0

#584 Fix CI failure: Add config to `FakeAsyncBeaconChainDB.__init__`
  tests/core/p2p-proto/bcc/helpers.py
  tests/core/p2p-proto/bcc/test_receive_server.py
Labels: eth2.0

#566 Extract low level peer networking into transport class
  p2p/p2p_proto.py
  p2p/peer.py
  p2p/protocol.py
  p2p/tools/paragon/helpers.py
  p2p/tools/paragon/proto.py
  p2p/transport.py
  setup.py
  tests/core/p2p-proto/bcc/helpers.py
  tests/core/p2p-proto/test_server.py
  tests/p2p/test_auth.py
  trinity/protocol/bcc/peer.py
  trinity/protocol/bcc/proto.py
  trinity/protocol/common/peer.py
  trinity/protocol/common/validators.py
  trinity/protocol/eth/proto.py
  trinity/protocol/les/proto.py
  trinity/server.py
Labels: PR state: needs review

#600 Move `hash_eth2` to `eth2/_utils/hash.py`
  eth2/_utils/hash.py
  eth2/_utils/merkle/common.py
  eth2/_utils/merkle/normal.py
  eth2/_utils/merkle/sparse.py
  eth2/beacon/_utils/random.py
  eth2/beacon/deposit_helpers.py
  eth2/beacon/helpers.py
  eth2/beacon/state_machines/forks/serenity/block_processing.py
  eth2/beacon/tools/builder/initializer.py
  tests/eth2/beacon/_utils/test_hash.py
  tests/eth2/beacon/db/test_beacon_chaindb.py
  tests/eth2/beacon/state_machines/forks/test_serenity_epoch_processing.py
  tests/eth2/beacon/test_deposit_helpers.py
  tests/eth2/beacon/test_epoch_processing_helpers.py
  tests/eth2/beacon/test_helpers.py
  tests/eth2/merkle-utils/test_merkle_trees.py
  tests/eth2/merkle-utils/test_sparse_merkle_trees.py
  tests/plugins/eth2/beacon/helpers.py
  trinity/plugins/eth2/network_generator/plugin.py
Labels: eth2.0

#601 Bump py-ssz to 0.1.0a8
  setup.py
Labels: eth2.0

#602 Reorg module path and extract CI
  .circleci/config.yml
  eth2/beacon/genesis.py
  eth2/beacon/tools/builder/initializer.py
  tests/eth2/beacon/helpers.py
  tests/eth2/core/beacon/_utils/test_random.py
  tests/eth2/core/beacon/chains/conftest.py
  tests/eth2/core/beacon/chains/test_beacon_chain.py
  tests/eth2/core/beacon/chains/test_chains.py
  tests/eth2/core/beacon/conftest.py
  tests/eth2/core/beacon/db/test_beacon_chaindb.py
  tests/eth2/core/beacon/state_machines/forks/test_fork_classes.py
  tests/eth2/core/beacon/state_machines/forks/test_serenity_block_attestation_validation.py
  tests/eth2/core/beacon/state_machines/forks/test_serenity_block_attester_slashing_validation.py
  tests/eth2/core/beacon/state_machines/forks/test_serenity_block_processing.py
  tests/eth2/core/beacon/state_machines/forks/test_serenity_block_proposer_slashing_validation.py
  tests/eth2/core/beacon/state_machines/forks/test_serenity_block_validation.py
  tests/eth2/core/beacon/state_machines/forks/test_serenity_block_voluntary_exit_validation.py
  tests/eth2/core/beacon/state_machines/forks/test_serenity_epoch_processing.py
  tests/eth2/core/beacon/state_machines/forks/test_serenity_operation_processing.py
  tests/eth2/core/beacon/state_machines/test_demo.py
  tests/eth2/core/beacon/state_machines/test_state_transition.py
  tests/eth2/core/beacon/test_beacon_validation.py
  tests/eth2/core/beacon/test_committee_helpers.py
  tests/eth2/core/beacon/test_deposit_helpers.py
  tests/eth2/core/beacon/test_epoch_processing_helpers.py
  tests/eth2/core/beacon/test_genesis.py
  tests/eth2/core/beacon/test_helpers.py
  tests/eth2/core/beacon/test_validator_status_helpers.py
  tests/eth2/core/beacon/tools/builder/test_builder_validator.py
  tests/eth2/core/beacon/types/test_attestation.py
  tests/eth2/core/beacon/types/test_attestation_data.py
  tests/eth2/core/beacon/types/test_attestation_data_and_custody_bit.py
  tests/eth2/core/beacon/types/test_attester_slashings.py
  tests/eth2/core/beacon/types/test_block.py
  tests/eth2/core/beacon/types/test_crosslink_record.py
  tests/eth2/core/beacon/types/test_deposit_data.py
  tests/eth2/core/beacon/types/test_deposit_input.py
  tests/eth2/core/beacon/types/test_deposits.py
  tests/eth2/core/beacon/types/test_eth1_data.py
  tests/eth2/core/beacon/types/test_eth1_data_vote.py
  tests/eth2/core/beacon/types/test_fork.py
  tests/eth2/core/beacon/types/test_pending_attestation_record.py
  tests/eth2/core/beacon/types/test_proposer_slashings.py
  tests/eth2/core/beacon/types/test_slashable_attestation.py
  tests/eth2/core/beacon/types/test_states.py
  tests/eth2/core/beacon/types/test_transfer.py
  tests/eth2/core/beacon/types/test_validator_record.py
  tests/eth2/core/beacon/types/test_voluntary_exits.py
  tests/eth2/fixtures-tests/state-fixtures/test_minimal_state.py
  tests/eth2/hash-utils/test_hash.py
  tox.ini
Labels: eth2.0

#604 Make test_demo.py to another CI job and mock the BLS verification
  .circleci/config.yml
  tests/eth2/conftest.py
  tests/eth2/core/beacon/conftest.py
  tests/eth2/integration/test_demo.py
  tox.ini
Labels: eth2.0

#630 Shutdown networkdb plugin on bad database
  trinity/plugins/builtin/network_db/plugin.py
Labels: PR state: needs review

#624 Disconnect reason handling and tracking
  p2p/peer.py
  p2p/peer_pool.py
Labels: PR state: needs review

#629 Blacklist peers who disconnect too quickly
  p2p/constants.py
  p2p/peer.py
Labels: PR state: needs review

#625 Candidate backend API now provides all connected remotes
  p2p/peer_backend.py
  p2p/peer_pool.py
Labels: PR state: needs review

#445 Release notes for v0.1.0-alpha.24
  docs/release_notes/trinity.rst
Labels: Release Notes

#626 relocate WrongGenesis and WrongNetwork to trinity
  p2p/exceptions.py
  trinity/constants.py
  trinity/exceptions.py
  trinity/protocol/eth/peer.py
  trinity/protocol/les/peer.py
Labels: PR state: needs review

#653 Change hexlified-bytes to raw-bytes
  libp2p/p2pclient/datastructures.py
  libp2p/p2pclient/p2pclient.py
  setup.py
  tests/libp2p/p2pclient/test_datastructures.py
Labels: PR state: needs review, eth2.0

#627 remove async from blacklist tracker methods
  p2p/peer_pool.py
  p2p/tracking/connection.py
  tests/core/network-db/test_blacklist_connection_tracking.py
  tests/core/network-db/test_connection_tracker_server.py
  trinity/plugins/builtin/network_db/connection/server.py
  trinity/plugins/builtin/network_db/connection/tracker.py
Labels: PR state: needs review

#628 refactor blacklist tracking API to allow explicit expiration
  p2p/peer.py
  trinity/plugins/builtin/network_db/connection/tracker.py
Labels: PR state: needs review

#652 Implement encryption and decryption functions
  p2p/discv5/__init__.py
  p2p/discv5/constants.py
  p2p/discv5/encryption.py
  tests/p2p/discv5/test_encryption.py
Labels: comp: p2p, eth2.0

#543 Track metadata abount peers on connection
  p2p/peer.py
  tests/core/p2p-proto/test_peer_metadata_tracker.py
  trinity/db/orm.py
  trinity/plugins/builtin/network_db/eth1_peer_db/__init__.py
  trinity/plugins/builtin/network_db/eth1_peer_db/events.py
  trinity/plugins/builtin/network_db/eth1_peer_db/server.py
  trinity/plugins/builtin/network_db/eth1_peer_db/tracker.py
  trinity/plugins/builtin/network_db/plugin.py
  trinity/protocol/common/peer.py
Labels: PR state: needs review
